### ISSUE TITLE
endpoint listing?

### ISSUE THREAD

**Issue by dustin** [KonradIT/gopro-plus-api#1]
I'm curious whether you know of any of the other endpoints that can be used here?

The token and listing parts are super helpful for ensuring I at least know what I've got stored at GoPro Plus, but would you happen to know how to fetch media?

**Comment by dustin** [comment]
I've RE'd pretty much the whole api surface for dustin/gopro-plus -- it's not simple documentation, but it's doing all the things.

**Comment by KonradIT** [comment]
Neat! I ended up shelving the effort for the time being, but now that I have 1 year of free Plus I'll resume this library.

**Comment by dustin** [comment]
I've built a fairly complete suite of tools at github.com/dustin/gopro built on the client API I RE'd.  You can see the doc overview at https://dustin.github.io/gopro-plus/

I've not documented the actual API surface, in a way other than in my code, but if you have any questions, let me know.  I started a [Discussions](https://github.com/dustin/gopro-plus/discussions/1) thing to capture some of this.
